import { keyMirror } from '../utils/index';

const ToolTypes = keyMirror({
  ADD_TO_FAVORITES: null,
  ASSIGN_DOC: null,
  BACK_TO_PARENT: null,
  CONTEXT_MENU: null,
  CREATE_DOC: null,
  CREATE_TAG: null,
  CREATE_TAG_ROOT: null,
  DELETE_DOC: null,
  DELETE_TAG: null,
  EXECUTION_LOG: null,
  EXPORT_AS_DOC: null,
  EXPORT_AS_IMG: null,
  EXPORT_AS_PDF: null,
  EXPORT_AS_WEB: null,
  EXPORT_AS_XLS: null,
  FAST_BACKWARD: null,
  FAST_FORWARD: null,
  LOG_OUT: null,
  MOVE_TAG: null,
  PAGE_NUMBER: null,
  PRINT: null,
  REMOVE_FROM_FAVORITES: null,
  RENAME_DOC: null,
  RENAME_TAG: null,
  SCHEDULE_DOC: null,
  SHARE_DOC: null,
  SORT_BY_DOCUMENT_NAME: null,
  SORT_BY_LAST_MODIFIED: null,
  SORT_BY_MODIFIED_BY: null,
  SORT_ORDER_ASC: null,
  SORT_ORDER_DESC: null,
  STEP_BACKWARD: null,
  STEP_FORWARD: null,
  TOGGLE_ACTION_MENU: null,
  TOGGLE_DOC_MENU: null,
  TOGGLE_EXPORT_MENU: null,
  TOGGLE_PARAMETERS_PANE: null,
  TOGGLE_PROPERTIES_PANE: null,
  TOGGLE_SEARCH_PANE: null,
  TOGGLE_SIDEBAR: null,
  TOGGLE_SORT_MENU: null,
  TOGGLE_TAG_MENU: null,
  TOGGLE_TOC_PANE: null,
});

export default ToolTypes;
